name: Update Posts

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: node generate-posts-info.js

    - name: Check for changes
      id: check_changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A  # Stage all changes in the repository
        if git diff-index --quiet HEAD; then
          echo "No changes detected"
          echo "changes=false" >> $GITHUB_ENV
        else
          echo "Changes detected"
          echo "changes=true" >> $GITHUB_ENV
        fi

    - name: Commit and push changes
      if: env.changes == 'true'
      run: |
        git commit -m 'auto updated posts'
        git push
